---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    "api-approved.kubernetes.io": "https://github.com/kubernetes/enhancements/pull/1870"
  name: noderesourcetopologies.topology.k8s.io
spec:
  group: topology.k8s.io
  version: v1alpha1
  versions:
    - name: v1alpha1
      served: true
      storage: true
  scope: Cluster
  validation:
    openAPIV3Schema:
      type: object
      properties:
        topologyPolicy:
          type: string
        nodes:
          type: array
          items:
            type: object
            properties:
              numaID:
                type: integer
              resources:
                type: object
                additionalProperties:
                  type: string
  names:
    plural: noderesourcetopologies
    singular: noderesourcetopology
    kind: NodeResourceTopology
    shortNames:
      - node-res-topo
