---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: noderesourcetopologies.node.k8s-test.io
spec:
  group: node.k8s-test.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            nodes:
              type: array
              items:
                type: object
                properties:
                  numaID:
                    type: integer
                  resources:
                    type: object
                    additionalProperties:
                      type: string
  scope: Namespaced
  names:
    plural: noderesourcetopologies
    singular: noderesourcetopology
    kind: NodeResourceTopology
    shortNames:
      - node-res-topo
