---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: node-topology-resources.k8s.cncf.io
spec:
  group: k8s.cncf.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            nodes:
              type: array
              items:
                type: object
                properties:
                  numaID:
                    type: integer
                  resources:
                    type: object
                    additionalProperties:
                      type: string
  scope: Namespaced
  names:
    plural: node-topology-resources
    singular: node-topology-resource
    kind: NodeResourceTopology
    shortNames:
      - node-topology-res
